# Generated by Django 2.2.1 on 2019-07-11 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingCount',
            new_name='ingredientCount',
        ),
    ]
