# Generated by Django 2.2.1 on 2019-07-09 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddNewRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=550)),
                ('image', models.ImageField(upload_to='photos')),
                ('ingredients', models.CharField(max_length=5500)),
                ('preparation', models.CharField(max_length=5500)),
                ('tips', models.CharField(max_length=550)),
                ('nutrition', models.CharField(max_length=550)),
            ],
        ),
    ]
