# Generated by Django 2.2.1 on 2019-07-09 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_addnewrecipe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddNewRecipe',
        ),
    ]
