# Generated by Django 2.2.1 on 2019-07-10 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20190709_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fruit',
            name='recipe_ptr',
        ),
        migrations.RemoveField(
            model_name='meat',
            name='recipe_ptr',
        ),
        migrations.RemoveField(
            model_name='vegetable',
            name='recipe_ptr',
        ),
        migrations.DeleteModel(
            name='Appetizer',
        ),
        migrations.DeleteModel(
            name='Fruit',
        ),
        migrations.DeleteModel(
            name='Meat',
        ),
        migrations.DeleteModel(
            name='Vegetable',
        ),
    ]
